apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab02
spec:
  selector:
    matchLabels:
      app: lab02
  replicas: 1
  #strategy, para que actualice el POD,no haya tiemmpo de demora o sin conexion, remplaza imagenes, "crea una nueva y remplaza"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: lab02
    spec:
      containers:
        - name: lab02sut
          image: mzegarra/lab02sut:latest
          #readinessProbe, intentas intentar, hasta que este listo, uan vez este listo, este se va a conectar 
          readinessProbe:
             httpGet:
               path: /actuator/health
               port: 7071
             #que tanto demora cargar estecontenedor, 25 segundos  
             initialDelaySeconds: 25
             periodSeconds: 10
             timeoutSeconds: 10
             successThreshold: 1
             failureThreshold: 3
             # kubernees, mata si es que no contesta
          livenessProbe:
             httpGet:
               path: /actuator/health
               port: 7071
            # initialDelaySeconds: verificac cada 10 segundos, debe ser mayor que el de arriba. 
             initialDelaySeconds: 30
             periodSeconds: 10
             timeoutSeconds: 10
             successThreshold: 1
            # verifica cada 3 veces. en cada(10segundos)
             failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              #cpu: 2000m se satura
              memory: 256Mi
            requests:
              cpu: 100m
              #cpu: 2000m se satura
              memory: 128Mi          
          ports:
            - containerPort: 7071
          envFrom:
            - configMapRef:
                name: ms-configurations
---
apiVersion: v1
kind: Service
metadata:
  name: lab02
  labels:
    app: lab02
spec:
  ports:
    - port: 7071
      targetPort: 7071
  selector:
    app: lab02
  type: ClusterIP

---
# este cambio. hace HPA. crece PODS de manera horizontal
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lab02
  labels:
    app: lab02
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab02
  targetCPUUtilizationPercentage: 60