apiVersion: v1
kind: ConfigMap
metadata:
  name: configserver-settings
  labels:
    app: configserver
data:
  GIT_URI: "https://github.com/dperezg2017/tci-config-dev.git"
  GIT_USER: "dperezg2017"
  GIT_PWD: "2472215Yo"
  KEYSTORE_PWD: "YOU_KEYSTORE_PASSWORD"
  KEYSTORE_ALIAS: "YOU_CONFIG_SERVER_KEY"
  KEYSTORE_SECRET: "YOU_KEYSTORE_PASSWORD"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: mzegarra/lab03sut
        ports:
          - containerPort: 8888
        envFrom:
          - configMapRef:
              name: configserver-settings
        volumeMounts:
          - name: configserver-key
            mountPath: /config-server.jks
      volumes:
        - name: configserver-key
          secret:
            secretName: configserver-key

---
## CREAR SERVICE PARA CONFGI SERVER
apiVersion: v1
kind: Service
metadata:
  name: configserver
  labels:
    app: configserver
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: configserver
  type: ClusterIP
  #type: LoadBalancer
  #targetPort: depende de con que peurto este el contenedor 